// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwjs0AAcBf2NlIwyDzTElEJ4WQLM3AFbw',
    appId: '1:398706348477:web:7f62c5344c886fbee382d4',
    messagingSenderId: '398706348477',
    projectId: 'pos701-c070d',
    authDomain: 'pos701-c070d.firebaseapp.com',
    storageBucket: 'pos701-c070d.firebasestorage.app',
    measurementId: 'G-7CC23BQK4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0mx_nepnE3YK0r-Q9PVwVplfh8kFE-CQ',
    appId: '1:398706348477:android:2a107452515dfa47e382d4',
    messagingSenderId: '398706348477',
    projectId: 'pos701-c070d',
    storageBucket: 'pos701-c070d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-nB-PfPc6lSfv_x4qOjugTb9TAZZSWM8',
    appId: '1:398706348477:ios:dea3f02b24ba4811e382d4',
    messagingSenderId: '398706348477',
    projectId: 'pos701-c070d',
    storageBucket: 'pos701-c070d.firebasestorage.app',
    iosBundleId: 'com.office701.pos701',
  );
}
